port: 8080
db_user: "admin"
db_password: "#r)Gw^dT$w2Q9Nn"
db_host: "schoolapps.ccvepiw6k7sc.ap-southeast-1.rds.amazonaws.com"
db_port: 3306
db_name: "test_golang"
max_idle_conns: 10
max_open_conns: 100
